$(document).ready(function(){


	$("#degree").click(function(){
		$("#d11").slideToggle("slow");
	});
	$("#branch").click(function(){
		$("#b1").slideToggle("slow");
	});
	$("#college").click(function(){
		$("#c1").slideToggle("slow");
	});
	$("#cgpa").click(function(){
		$("#cg").slideToggle("slow");
	});
	$("#d1").mouseover(function(){
	$("#d1").css("background-color","#cd853f");
		});
	$("#d1").mouseout(function(){
		$("#d1").css("background-color","#E3EDD8");
	});
	$("#d2").mouseover(function(){
	$("#d2").css("background-color","#cd853f");
		});
	$("#d2").mouseout(function(){
		$("#d2").css("background-color","#E3EDD8");
	});
	$("#d3").mouseover(function(){
	$("#d3").css("background-color","#cd853f");
		});
	$("#d3").mouseout(function(){
		$("#d3").css("background-color","#E3EDD8");
	});
	$("#d4").mouseover(function(){
	$("#d4").css("background-color","#cd853f");
		});
	$("#d4").mouseout(function(){
		$("#d4").css("background-color","#E3EDD8");
	});
	$("#d5").mouseover(function(){
	$("#d5").css("background-color","#cd853f");
		});
	$("#d5").mouseout(function(){
		$("#d5").css("background-color","#E3EDD8");
	});
	$("#d6").mouseover(function(){
	$("#d6").css("background-color","#cd853f");
		});
	$("#d6").mouseout(function(){
		$("#d6").css("background-color","#E3EDD8");
	});
	$("#d7").mouseover(function(){
	$("#d7").css("background-color","#cd853f");
		});
	$("#d7").mouseout(function(){
		$("#d7").css("background-color","#E3EDD8");
	});
	$("#d8").mouseover(function(){
	$("#d8").css("background-color","#cd853f");
		});
	$("#d8").mouseout(function(){
		$("#d8").css("background-color","#E3EDD8");
	});
	$("#d9").mouseover(function(){
	$("#d9").css("background-color","#cd853f");
		});
	$("#d9").mouseout(function(){
		$("#d9").css("background-color","#E3EDD8");
	});
	$("#cd").click(function(){
		$("#collegedetails").slideToggle("slow");
	});
	$("#hsd").click(function(){
		$("#hrsd").slideToggle("slow");
	});
		$("#hrsc").click(function(){
			$("#s1").slideToggle("slow");
		})
	$("#branch1").click(function(){
		$("#b11").slideToggle("slow");
	});

	$("#percentage").click(function(){
		$("#pg").slideToggle("slow");
	});
	$("#hsd1").click(function(){
		$("#hrsd1").slideToggle("slow");
	});
		$("#hrsc1").click(function(){
			$("#s11").slideToggle("slow");
		})
	$("#branch11").click(function(){
		$("#b2").slideToggle("slow");
	});

	$("#percentage1").click(function(){
		$("#pg1").slideToggle("slow");
	});
	$("#aoi").click(function(){
		$("#aoidetails").slideToggle("slow");
	});
	$("#ts").click(function(){
		$("#skills").slideToggle("slow");
	});
	$("#pc").click(function(){
		$("#project").slideToggle("slow");
	});
	$("#cca").click(function(){
		$("#curricular").slideToggle("slow");
	});
	$("#workshop").click(function(){
		$("#wsp").slideToggle("slow");
	});
	$("#extra").click(function(){
		$("#eca").slideToggle("slow");
	});
	$("#resp").click(function(){
		$("#ru").slideToggle("slow");
	});
});